version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: prestashop_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashop
      MYSQL_PASSWORD: prestashop
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"

  prestashop:
    image: prestashop/prestashop:latest
    container_name: prestashop_app
    restart: always
    depends_on:
      - db
    environment:
      DB_SERVER: db
      DB_NAME: prestashop
      DB_USER: prestashop
      DB_PASSWORD: prestashop
    volumes:
      - prestashop_data:/var/www/html
    ports:
      - "8080:80"

volumes:
  db_data:
  prestashop_data:
